### ISSUE TITLE
Problem with updates in home assistant supervised

### ISSUE THREAD

**Issue by RunnerLexico** [zigbee2mqtt/hassio-zigbee2mqtt#171]
**Description of problem:**
Hello,
I found a little problem with my HASS installation. Yesterday I received a new zigbee valve for my radiator (TuYa HY367, Clone of HY368). I tried to connect it to my zigbee2mqtt addon. It was not compatible with zigbee2mqtt.
I recognized that I didnt receive updates for my Zigbee2mqtt addon for a long time and thought that could be a fix for that concern. Then i started to search for the reason of my update problem. I recognized that I used the repository "https://www.zigbee2mqtt.io" for the supervisor addon-store. I received version 1.18.1-1 from that repository, the valve is not recognized with that version.
After a little time of research I found another repository link for the hass addon: "https://github.com/zigbee2mqtt/hassio-zigbee2mqtt". When I installed and used that, i received version 1.21.0-4 and the vavle was recognized correctly. 
But after upgrading I saw that my window contacts are not recognized anymore as sensors, they had the same problem as the valve with version 1.18.11. 

So I decided to downgrade back to 1.18.11. My window sensors are working again but now the valve is not working anymore. How is that possible? What is the difference of these two repository URLs?

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.18.1-1 start /app
AND
> zigbee2mqtt@1.21.0-4 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
Not needed now.
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.8.7
Supervisor: supervisor-2021.06.8
Operating System: Home Assistant OS 6.2
```

**Your logs from Home Assistant Supervisor**
```
Not needed now.
```

**Comment by ciotlosm** [comment]
Zigbee2mqtt repository initially was developed and stored under https://github.com/danielwelch/hassio-zigbee2mqtt but later was refactored with better structure (s6, detection for mqtt credentials, etc.) under the new org and now was moved into https://github.com/zigbee2mqtt/hassio-zigbee2mqtt. 

The older repo was kept up to date for a while in sync, but now is no longer updated, so the direction is the new repository. 

Your window contacts not being recognised could probably be a problem, but in order to report and fix it, this must be done under https://github.com/Koenkk/zigbee2mqtt/issues as that is a problem with the Core. 

You can check https://github.com/danielwelch/hassio-zigbee2mqtt/pull/489 for a list of improvements when the migration was done.

**Comment by RunnerLexico** [comment]
Thanks for your really fast reply. I upgraded my installation and found an issue in the core project, it should be fixed in the next version. (1.21.1)

Thanks for your support!
Jan
