### ISSUE TITLE
Zigbee2mqtt 1.17.1

### ISSUE THREAD

**Issue by Mr-Groch** [zigbee2mqtt/hassio-zigbee2mqtt#20]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
Zigbee2mqtt 1.17.1 has been released few days ago, when this addon will be udpated?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Home Assistant**

**Comment by shirou93** [comment]
I'm waiting too.

**Comment by jd1900** [comment]
Same here.

I though this was the "newer" version, most updated. But it is just the opposite.

**Comment by Mr-Groch** [comment]
Yeah, 3 months in a row, it is updated few days after danielwelch's repository

**Comment by shirou93** [comment]
@cciotlosm this repo is dropped?

**Comment by Fridolin34** [comment]
Hmm. I've switched from another add-on to this one, because I thought this would be the 'better' one. More frequently updated or newer built or ... I don't know. Unfortunately, I've forgotten the URL of the other repository, so I cannot switch back and basically I don't want to spend the time to switch. But maybe it's needed.

What is your opinion? Which one is the add on to choose?

**Comment by ciotlosm** [comment]
This add-on will become the official. Just had some troubles making the update. There are two PRs to make the switch, just didn't get to it.

**Comment by ciotlosm** [comment]
This is now released.
