### ISSUE TITLE
Allow configuration of MQTT password, base_topic and  network_key through addon config rather than configuration.yaml

### ISSUE THREAD

**Issue by fliphess** [zigbee2mqtt/hassio-zigbee2mqtt#317]
**Description of problem:**

Now that the MQTT `password`, `base_topic`, `network_key`,  is migrated to configuration.yaml, these cannot be retrieved from the home-assistant `secret.yaml` anymore, which results in plain text passwords and other private data in the configuration file. 

As a result the only way to keep these settings private is adding the full config file to the `.gitignore` of my version control.

Preferably the config file can be kept in version control for restore purposes or when migrating to another server.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.25.0-1
```

Cause: I almost added my zigbee2mqtt to my public git repository due to the breaking changes in 1.25.0-1

I would love to keep my `configuration.yaml` in a VCS while hiding the configuration elements I want to keep private using the `!secret` mechanism in the home assistant addon configuration instead of having to exclude the full config file in my `.gitignore`, as it would make restoring the functionality after hardware failure much easier when having the original config file.

**Comment by mdegat01** [comment]
The MQTT password can still be set in the addon configuration. In fact its one of the few things you have to set via the addon configuration since the addon will not start without a valid MQTT configuration. So you can still use `!secret` there.

That being said, `!secret` references have always been substituted with the actual secret in plaintext in the configuration.yaml file that Z2M uses. This is because `!secret` is a home assistant thing, not a Z2M or native YAML thing. Z2M is what is interpreting its own `configuration.yaml` file and it has no clue what `!secret` means so that would just fail.

If your goal is to put the `configuration.yaml` of Z2M in version control then what you should ask for is the ability to set the matching [environmental variables](https://www.zigbee2mqtt.io/guide/configuration/#environment-variables). Z2M (like many dockerized applications) supports overriding pieces of its config via environmental variables. So if the addon config provided options to let you set the following environmental variables:

- `ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD`
- `ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC` (why is this a secret?)
- `ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY`

Then you could keep those values out of the `configuration.yaml` file using Z2M's native mechanism for doing so.
