### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by fontes31** [zigbee2mqtt/hassio-zigbee2mqtt#339]
**Description of problem:**

Hi,

I have installed zigbee2mqtt on home assisntant, witht he dongle - " /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_90_A6_9D-if00-port0"
after install the zigbee2mqtt i have the following error;

Zigbee2MQTT:info  2022-05-21 08:33:58: Starting zigbee-herdsman (0.14.27)
Zigbee2MQTT:debug 2022-05-21 08:33:58: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{}}'
2022-05-21T07:33:58.820Z zigbee-herdsman:adapter No path provided, auto detecting path
Zigbee2MQTT:error 2022-05-21 08:33:58: Error while starting zigbee-herdsman

and 502: Bad Gateway, what iam missing?

on my configuration i have this:

![imagem](https://user-images.githubusercontent.com/7975962/169641332-1703bd27-94d4-42a9-b847-9cbc70d6364d.png)

```

**Comment by DJBenson** [comment]
Try putting the path to your serial adapter in the config. Z2M can't find it.

**Comment by fontes31** [comment]
i add it below the topic "serial"?
 the device path should be this - /dev/ttyUSB0  ? right?

**Comment by DJBenson** [comment]
It is much better to use the friendly device name as the tty* devices can change between reboots. Here's my config for the Sonoff dongle;

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/1013909/169645696-22ced29f-fa39-44b4-a199-fed40b32928d.png">

**Comment by fontes31** [comment]
now i have the configuration like this:

![imagem](https://user-images.githubusercontent.com/7975962/169645633-434210f7-a4af-4800-b8f8-99d080db0394.png)

then i have the following error:

![imagem](https://user-images.githubusercontent.com/7975962/169645702-121587c7-4087-48c3-a6d0-bf5443029e42.png)

**Comment by DJBenson** [comment]
It looks like it's started though?

**Comment by fontes31** [comment]
i still have

![imagem](https://user-images.githubusercontent.com/7975962/169645806-e8b98a07-3493-4497-8695-c27bc3689004.png)

**Comment by DJBenson** [comment]
I'm not sure why you've got config in the serial section other than the port - switch into yaml mode and make sure your indentations are correct as I have both permot_join and frontend in my config but neither show in the serial section as you have shown.

**Comment by fontes31** [comment]
the error on the log:
![imagem](https://user-images.githubusercontent.com/7975962/169645847-d9a3751d-3288-413b-ab11-be88cc7e57a8.png)

**Comment by fontes31** [comment]
> 

![imagem](https://user-images.githubusercontent.com/7975962/169645875-71e854b9-ef3c-461c-941a-52dd65321a19.png)

**Comment by DJBenson** [comment]
Your indentation is wrong. No idea if that's the cause but sort out your config 😀

Both permit_join and frontend should be aligned to the left, no indentations like this;

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1013909/169645932-7ffaa4a1-325a-4b88-b664-6fe94eafe745.png">

**Comment by fontes31** [comment]
it is ok now, i think

![imagem](https://user-images.githubusercontent.com/7975962/169645933-1055be7a-9934-4843-8c5e-b2fc64177dda.png)

**Comment by DJBenson** [comment]
If the frontend is up you've fixed it 😀

**Comment by fontes31** [comment]
the mqtt part is ok?

**Comment by fontes31** [comment]
when i press permit join (all) i have this:

![imagem](https://user-images.githubusercontent.com/7975962/169646205-b0ab29eb-2706-46f5-9924-ed5a6f8b0b93.png)

**Comment by DJBenson** [comment]
Your config still looks incomplete. You seem to be missing (compared to my config);
- pan_id
- ext_pan_id
- channel
- network_key

**Comment by DJBenson** [comment]
I'm fairly sure your issue is that your network doesn't have a network key.

**Comment by DJBenson** [comment]
My install pre-dates all these things being configurable via the UI so check in the UI if the network key has been generated - it might have been generated on first start so you just need to restart the container for it to work.

**Comment by fontes31** [comment]
the network config should be on configuration.yaml?

now i have this

![imagem](https://user-images.githubusercontent.com/7975962/169647173-3c1db2f9-bfd4-4465-9d46-6122a6f675ce.png)

**Comment by DJBenson** [comment]
I can't see network_key in the UI so presume it HAS to be in the configuration file.

Add this and restart;

> advanced:
>   network_key: GENERATE

making sure indentation is correct then restart the container. GENERATE should be replaced with a valid key.

**Comment by DJBenson** [comment]
Here's a full, working but redacted config from my environment;

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/1013909/169647474-fca121fe-0652-4cf9-9a8e-4f815f61c6fd.png">

**Comment by AlexVelky** [comment]
Hi Guys,
i have completely the same issue today, but i am pretty sure that it was working fine 2 days ago, and few months already since i've configured it. And i did no change in last two or more days. Today morning i've just noticed that none of my sensors are updating the status, and none switch conected via Z2M is  working anymore. I've tried restore from backup two days back, completely un-install and install Zigbee@Mqtt addon again, with full reconfiguration but nothing helped. I've even tried 3 other  USB coorinator dongles and all other USB port on my server to be sure that it is not HW issue, but it is not. 

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Kernel version 5.10.0-7-amd64

here is the same error in the log file :

[13:50:10] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1 start
> node index.js
Zigbee2MQTT:error 2022-05-21 13:50:34: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-05-21 13:50:34: Failed to start zigbee
Zigbee2MQTT:error 2022-05-21 13:50:34: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-05-21 13:50:34: Exiting...
Zigbee2MQTT:error 2022-05-21 13:50:34: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:110:5)

[13:50:35] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1 start
> node index.js
Zigbee2MQTT:error 2022-05-21 13:50:59: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-05-21 13:50:59: Failed to start zigbee
Zigbee2MQTT:error 2022-05-21 13:50:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-05-21 13:50:59: Exiting...
Zigbee2MQTT:error 2022-05-21 13:50:59: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:110:5)
[13:51:00] INFO: Handing over control to Zigbee2mqtt Core ...

and it is the same over and over again

for few minutes after Z2M restart i also have message "502: Bad Gateway" in GUI, but after an hour or so, the GUI start working fine, but the issue is still there, no device status updates at all, not possible to add any new device.

here is my /config/zigbee2mqtt/configuration.yaml

external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: z2m
  password: ###########
  server: mqtt://core-mosquitto:1883
 serial:
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0a36860acdc9eb11b94b914f1d69213e-if00-port0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false

**Comment by fontes31** [comment]
I will configure it better.
Can I have a dongle USB for zigbee and other dongle for zigbee2mqtt in the same ha?
