### ISSUE TITLE
no addon after repository is added

### ISSUE THREAD

**Issue by marel1234** [zigbee2mqtt/hassio-zigbee2mqtt#388]
### Description of the issue

When 
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
is added as new repository there is no zigbee2mqtt addon shown in the store after restart

### Addon version

v1.27.2-1

### Platform

Home Assistant 2022.9.6 
Supervisor 2022.09.1 
Operating System 9.0 
Frontend 20220907.2 - latest

**Comment by cociweb** [comment]
Hello,
Same annoying issue happened with me, but it's something with HA/supervisor, because, other repos behaves the same. I don't really get the holly manna, either: 
try logout-login, delete cookies, restart browser, restart HA+supervisor....
I've left for an hour, and the repo appeared in the meantime, I was able to install it after that.
Once more: it's independent from this addon. any new custom repos behaves like this. - anyway, adding new custom repo is not so frequent from the user/developer pov, so it's not reported as a permanent reproducable issue in Supervisor. If you got it, please report it there..

**Comment by marel1234** [comment]
Thanks you nice guys, logout - login worked for me too...
