### ISSUE TITLE
[Enhancement] Allow editing settings using built-in Zigbee2mqtt web interface

### ISSUE THREAD

**Issue by ewoutdenheijer** [zigbee2mqtt/hassio-zigbee2mqtt#41]
Zigbee2mqtt now has a pretty nice build in web interface. It's also possible to edit most configuration settings using the web interface. These config changes are overwritten by a restart of the add on. This makes the settings part of the interface unusable. All configuration needs to be done in the add on configuration. This is a pity, because the settings in the web interface are actually more comprehensive then what's being passed trough by the add on. (last_seen for example, is missing)

Perhaps it's worth considering to rely on zigbee2mqtt's native web interface for configuration from now on. That way you don't have to keep track of configuration options of zigbee2mqtt in the add on.

Alternatively, you could perhaps make this in itself an option?

**Comment by ciotlosm** [comment]
I'm not sure which is the best option, and we'll have to think of the best approach here. Z2M add-on is created to be compatible with the Supervisor to integrate seamlessly with Home Assistant. It will always require some sort of configuration and the Supervisor will expose probably in the future the options as a nice UI. 

There are probably two approaches:
- Find a way to disable configs from Z2M Supervisor interface and just use built in
- Find a way to detect if Z2M is running in Home Assistant with Supervisor and just hide the "configs" in the built-in UI. 


You have to consider that there are users out there that don't enable / use the built-in UI for Z2M because it consumes memory and they want their installation lightweight as well. 

I will mark this as a feature request to review at a later date.

**Comment by cmorlok** [comment]
I have played around with this new feature, and I realized that not only get the settings overwritten at start up, but also are the settings that I have made in the supervisor interface not shown the built in UI. So I have no idea which configuration is actually in use.

As a user, I would expect them to be in sync. So that I am able to edit them either in the supervisor or use the config UI. Alternatively, the options available in the supervisor should be reduced to the bare minimum, everything else is only configurable in the built-in UI. But then you would no longer be able to run the addon without using the UI. Or the build-in config should be disabled at all.

Until this is decided and implemented, a would recommend to add a warning to the addon doc to not use the built-in config.

**Comment by netweaver1970** [comment]
I would also allow the disabling of supervisor device/group config settings. 

Only the minimum settings should be done in the supervisor config, such as serial device/port, enable supervisor based device/group config(as fallback only) and specific mqtt server connection parameters. In line with other HA add-ons having a proper ui based config screen. 

If people still want yaml/json based text config, then they can enable it. But a perfectly working gui should be the 1st choice, this is 2021. In all areas of HA one can see more focus on ease of use and better ui.
Sticking to text based config for large amount of devices, only for lightweight reason is a bit sad.

Also, please document a migration scenario from a z2m standalone docker container to a z2m add-on install. 

For now I'm holding off my complete HA migration from my HA supervised install with separate z2m container to Hass OS with integrated z2m add-on, as I'll be losing too much functionality in the z2m area. I like z2m a lot but the gui makes it so much easier to control. I have 60+ devices, I'm not going the text based config route again.

Thanks for your efforts, I'll be keeping a close eye on the developments

**Comment by ciotlosm** [comment]
@cmorlok Happy to get a PR for a Documentation update for: "Until this is decided and implemented, a would recommend to add a warning to the addon doc to not use the built-in config."

@netweaver1970 
> Only the minimum settings should be done in the supervisor config, such as serial device/port, enable supervisor based device/group config(as fallback only) and specific mqtt server connection parameters. In line with other HA add-ons having a proper ui based config screen.

I agree that if there is a way to simplify add-on config now that the actual core offers a built-in UI, that should be the way to go, however doing breaking changes is not easy with such a diverse user base so I'd like to make sure we have all cases covered to do a good solution. 

> Sticking to text based config for large amount of devices, only for lightweight reason is a bit sad.

Keep in mind that Home Assistant Supervisor promised to add a better ui for the JSON config some time ago and when we packaged the add-on for the first time there was no alternative. The built-in UI is pretty new and was an experimental feature for some time. 

For people that don't want to use the built-in UI for memory of performance reasons we must find a good balance. The current setup with the config in the add-on UI is far better than asking them to SSH in or add another add-on for file management so there has to be a balance. I'm pretty much against forcing users to upgrade hardware just because we're dropping some functionality. (And i know having another add-on to manage files can be kept off, so not really required, but you get my point). 


What I think we need for next steps:
- Identify which are the minimum config settings that the add-on requires in order to function by itself
- See if there is a way to inject /override these without breaking other settings
- Verify how a migration can be done and document this
- Check if there is a way to still allow advanced configs (maybe without validation) for people that don't enable the built-in frontend or just specify in the docs to use alternate methods (like extra add-ons for file management directly)
- Check if there is a way to extract add-on specific configs (startup) from the rest in a separate file for easier management (@Koenkk )

Happy to get here feedback on which settings people think the add-on should manage at a minimum.

**Comment by ciotlosm** [comment]
I've done an initial parse, and there are things I'm unsure how would get supported. Also there are settings missing from the built-in UI (like `device_options`)

```
{
    "zigbee_shepherd_devices": "bool?", // > Yes, hack for devices.js https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/dev/common/rootfs/etc/cont-init.d/zigbee2mqtt.sh#L48 - Maybe auto-detect if required
    "zigbee_herdsman_debug": "bool?", // > Yes, debug option for startup  https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/dev/common/rootfs/etc/services.d/zigbee2mqtt/run
    "external_converters": [
        "str?" // > No, part of built-in UI config
    ],
    "data_path": "str", // > Yes, required to specify where to persist add-on data
    "devices": "str?", // > No, part of built-in UI config
    "groups": "str?", // > No, part of built-in UI config
    "homeassistant": "bool", // No, should be injected automatically as `true` (forced)
    "permit_join": "bool", // > No, part of built-in UI config
    "mqtt": {
        "base_topic": "str", // > No, part of built-in UI config
        "server": "str?", // > ??? , part of built-in UI config - How to support discovery?
        "ca": "str?", // No, part of built-in UI config 
        "key": "str?", // No, part of built-in UI config 
        "cert": "str?", // No, part of built-in UI config 
        "user": "str?", // > ??? , part of built-in UI config - How to support discovery?
        "password": "str?", // > ??? , part of built-in UI config - How to support discovery?
        "client_id": "str?", // No, part of built-in UI config 
        "keepalive": "int?", // No, part of built-in UI config 
        "version": "int?", // No, part of built-in UI config 
        "reject_unauthorized": "bool?", // No, part of built-in UI config 
        "include_device_information": "bool?", // No, part of built-in UI config 
        "force_disable_retain": "bool?" // No, part of built-in UI config 
    },
    "serial": { // > No, part of built-in UI config
        "port": "str",
        "disable_led": "bool?",
        "adapter": "match(^zstack|deconz|zigate|ezsp$)?"
    },
    "blocklist": [ // > No, part of built-in UI config
        "str?"
    ],
    "passlist": [ // > No, part of built-in UI config
        "str?"
    ],
    "advanced": { // > No, part of built-in UI config
        "pan_id": "int(0,65536)?",
        "ext_pan_id_string": "match(^(\\s*\\d+\\s*,){7}(\\s*\\d+\\s*)$)?",
        "channel": "int(11,26)?",
        "cache_state": "bool?",
        "cache_state_persistent": "bool?",
        "cache_state_send_on_startup": "bool?",
        "log_level": "match(^info|debug|warn|error$)?",
        "log_directory": "str?",
        "log_file": "str?",
        "log_rotation": "bool?",
        "timestamp_format": "str?",
        "baudrate": "int?",
        "rtscts": "bool?",
        "soft_reset_timeout": "int?",
        "adapter_concurrent": "int?",
        "adapter_delay": "int?",
        "network_key": [
            "int?"
        ],
        "network_key_string": "match(^(\\s*\\d+\\s*,){15}(\\s*\\d+\\s*)$)?",
        "last_seen": "match(^disable|ISO_8601|epoch)?",
        "elapsed": "bool?",
        "availability_timeout": "int?",
        "availability_blocklist": [
            "str?"
        ],
        "availability_passlist": [
            "str?"
        ],
        "report": "bool?",
        "homeassistant_discovery_topic": "str?",
        "homeassistant_status_topic": "str?",
        "homeassistant_legacy_triggers": "bool?",
        "ikea_ota_use_test_url": "bool?",
        "legacy_api": "bool?"
    },
    "device_options": { // ???, this should be part of the build-in UI
        "occupancy_timeout": "int?",
        "temperature_precision": "int?",
        "legacy": "bool?"
    },
    "device_options_string": "str?", // ???, this should be part of the build-in UI
    "queue": { // No ? - I don't see this in the options
        "delay": "int?",
        "simultaneously": "int?"
    },
    "experimental": { // > No, part of built-in UI config
        "transmit_power": "int?",
        "output": "str?"
    },
    "frontend": { // > Yes, and should also have the default to have show in sidebar working out of the box
        "host": "str?",
        "port": "int?"
    },
    "socat": { // Yes, required for startup
        "enabled": "bool?",
        "master": "str?",
        "slave": "str?",
        "options": "str?",
        "log": "bool?"
    }
}
```

At a minimum I think the config could look like:

```json
{
    "zigbee_herdsman_debug": "bool?",
    "data_path": "str",
    "frontend": {
        "port": "int?"
    },
    "socat": {
        "enabled": "bool?",
        "master": "str?",
        "slave": "str?",
        "options": "str?",
        "log": "bool?"
    }
}
```

**Comment by Koenkk** [comment]
Some device options can be configured by clicking on a device -> settings. But not specific ones like `occupancy_timeout`. @nurikk would it be possible to also allow those options here? Thinking about some simple key/value thing

**Comment by nurikk** [comment]
> Some device options can be configured by clicking on a device -> settings. But not specific ones like `occupancy_timeout`. @nurikk would it be possible to also allow those options here? Thinking about some simple key/value thing
> 
> @ciotlosm does it make sense to allow users change the frontend port? Isn't this hardcoded with the one used in the tab?

Yes, we can add additionalProperties support, so users can add they key/value pars. I will add this to my todo list

**Comment by ewoutdenheijer** [comment]
> 
> 
> I've done an initial parse, and there are things I'm unsure how would get supported. Also there are settings missing from the built-in UI (like `device_options`)
> 
> ```
> {
>     "zigbee_shepherd_devices": "bool?", // > Yes, hack for devices.js https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/dev/common/rootfs/etc/cont-init.d/zigbee2mqtt.sh#L48 - Maybe auto-detect if required
>     "zigbee_herdsman_debug": "bool?", // > Yes, debug option for startup  https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/dev/common/rootfs/etc/services.d/zigbee2mqtt/run
>     "external_converters": [
>         "str?" // > No, part of built-in UI config
>     ],
>     "data_path": "str", // > Yes, required to specify where to persist add-on data
>     "devices": "str?", // > No, part of built-in UI config
>     "groups": "str?", // > No, part of built-in UI config
>     "homeassistant": "bool", // No, should be injected automatically as `true` (forced)
>     "permit_join": "bool", // > No, part of built-in UI config
>     "mqtt": {
>         "base_topic": "str", // > No, part of built-in UI config
>         "server": "str?", // > ??? , part of built-in UI config - How to support discovery?
>         "ca": "str?", // No, part of built-in UI config 
>         "key": "str?", // No, part of built-in UI config 
>         "cert": "str?", // No, part of built-in UI config 
>         "user": "str?", // > ??? , part of built-in UI config - How to support discovery?
>         "password": "str?", // > ??? , part of built-in UI config - How to support discovery?
>         "client_id": "str?", // No, part of built-in UI config 
>         "keepalive": "int?", // No, part of built-in UI config 
>         "version": "int?", // No, part of built-in UI config 
>         "reject_unauthorized": "bool?", // No, part of built-in UI config 
>         "include_device_information": "bool?", // No, part of built-in UI config 
>         "force_disable_retain": "bool?" // No, part of built-in UI config 
>     },
>     "serial": { // > No, part of built-in UI config
>         "port": "str",
>         "disable_led": "bool?",
>         "adapter": "match(^zstack|deconz|zigate|ezsp$)?"
>     },
>     "blocklist": [ // > No, part of built-in UI config
>         "str?"
>     ],
>     "passlist": [ // > No, part of built-in UI config
>         "str?"
>     ],
>     "advanced": { // > No, part of built-in UI config
>         "pan_id": "int(0,65536)?",
>         "ext_pan_id_string": "match(^(\\s*\\d+\\s*,){7}(\\s*\\d+\\s*)$)?",
>         "channel": "int(11,26)?",
>         "cache_state": "bool?",
>         "cache_state_persistent": "bool?",
>         "cache_state_send_on_startup": "bool?",
>         "log_level": "match(^info|debug|warn|error$)?",
>         "log_directory": "str?",
>         "log_file": "str?",
>         "log_rotation": "bool?",
>         "timestamp_format": "str?",
>         "baudrate": "int?",
>         "rtscts": "bool?",
>         "soft_reset_timeout": "int?",
>         "adapter_concurrent": "int?",
>         "adapter_delay": "int?",
>         "network_key": [
>             "int?"
>         ],
>         "network_key_string": "match(^(\\s*\\d+\\s*,){15}(\\s*\\d+\\s*)$)?",
>         "last_seen": "match(^disable|ISO_8601|epoch)?",
>         "elapsed": "bool?",
>         "availability_timeout": "int?",
>         "availability_blocklist": [
>             "str?"
>         ],
>         "availability_passlist": [
>             "str?"
>         ],
>         "report": "bool?",
>         "homeassistant_discovery_topic": "str?",
>         "homeassistant_status_topic": "str?",
>         "homeassistant_legacy_triggers": "bool?",
>         "ikea_ota_use_test_url": "bool?",
>         "legacy_api": "bool?"
>     },
>     "device_options": { // ???, this should be part of the build-in UI
>         "occupancy_timeout": "int?",
>         "temperature_precision": "int?",
>         "legacy": "bool?"
>     },
>     "device_options_string": "str?", // ???, this should be part of the build-in UI
>     "queue": { // No ? - I don't see this in the options
>         "delay": "int?",
>         "simultaneously": "int?"
>     },
>     "experimental": { // > No, part of built-in UI config
>         "transmit_power": "int?",
>         "output": "str?"
>     },
>     "frontend": { // > Yes, and should also have the default to have show in sidebar working out of the box
>         "host": "str?",
>         "port": "int?"
>     },
>     "socat": { // Yes, required for startup
>         "enabled": "bool?",
>         "master": "str?",
>         "slave": "str?",
>         "options": "str?",
>         "log": "bool?"
>     }
> }
> ```
> 
> At a minimum I think the config could look like:
> 
> ```json
> {
>     "zigbee_herdsman_debug": "bool?",
>     "data_path": "str",
>     "frontend": {
>         "port": "int?"
>     },
>     "socat": {
>         "enabled": "bool?",
>         "master": "str?",
>         "slave": "str?",
>         "options": "str?",
>         "log": "bool?"
>     }
> }
> ```

Z2M won't start without being able to connect to the dongle. So that path is required (unless your dongle happens to be at the default path). That said. Perhaps Z2M could throw a warning in stead of an error even without a dongle. Otherwise it's quite easy to lock yourself out of the web interface for repairing misconfigurations. This also goes for native installations.

**Comment by ciotlosm** [comment]
@ewoutdenheijer that makes sense, I think there should be at least a separation of startup parameters and normal configs, that way we could also disable startup configs in the built-in ui when using it as an add-on

@nurikk is there a way to add to the todo list such a mechanism? (some sort of tagging for config parameters that allows for specific ones to not show in the UI). 

@Koenkk at the moment we still allow for port changes for the frontend because some users don't use ingress feature and want to customise it. I think I will keep that functionality even if we default to the correct ingress feature port.

**Comment by nurikk** [comment]
Since now additional device properties can be added, very bottom of device settings page + button

Additionally options can be flagged as `"readOnly": true`, to prevent user changes from UI.
<img width="1674" alt="Screenshot 2021-03-13 at 18 46 54" src="https://user-images.githubusercontent.com/1525421/111027662-93523d80-842c-11eb-86e5-0eeec093932f.png">

**Comment by eRJe79** [comment]
@nurikk was the + button (re)moved? I don't see it on v6.0.1.

I like to add the device specific `invert_cover` attribute in order to make the Legrand shutter switch 067776 work correctly. I've noticed the additional tab Settings (specific) which is under construction. Am I supposed to add this attribute in here when it is completed? Is there today a work around to still use `invert_cover`?

**Comment by nurikk** [comment]
> @nurikk was the + button (re)moved? I don't see it on v6.0.1.
> 
> I like to add the device specific `invert_cover` attribute in order to make the Legrand shutter switch 067776 work correctly. I've noticed the additional tab Settings (specific) which is under construction. Am I supposed to add this attribute in here when it is completed? Is there today a work around to still use `invert_cover`?

This feature yet to be fixed, meanwhile you can edit configuration.yaml and define any parameters you need

**Comment by eRJe79** [comment]
> This feature yet to be fixed, meanwhile you can edit configuration.yaml and define any parameters you need

I tried to edit the configuration.yaml (or devices.yaml) but the changes are not being taken and overwritten as soon as I use the GUI. Anything I am forgetting?

**Comment by netweaver1970** [comment]
This whole duality web config vs yaml config is so ill conceived. 

Holding on to the text based config due to 'poor' people using older, slow, less capable HW should be in 2021 a non issue. Plenty of examples to ditch yaml based config where it makes sense. Look at esphome, deconz etc...

Focus should be on 1 method. And I know which one will win

**Comment by nurikk** [comment]
> > This feature yet to be fixed, meanwhile you can edit configuration.yaml and define any parameters you need
> 
> I tried to edit the configuration.yaml (or devices.yaml) but the changes are not being taken and overwritten as soon as I use the GUI. Anything I am forgetting?

You need to restart z2m after editing configuration.yaml

**Comment by eRJe79** [comment]
@nurikk Thanks, that finally got me to understand I need to edit the configuration.yaml in the add-on configuration tab. Now I could see my changes taking effect. I also confirmed that changes in the devices.yaml are taking effect.

What I didn't succeed on is to make `invert_cover` working. In configuration.yaml I changed device_options: {} into
```
device_options:
  invert_cover: true
```

and in devices.yaml I tried several syntaxes based on what I read in the instructions or on forums

```
'0x00047400008fd937':
  friendly_name: Shutter_Office
  device_options: { invert_cover: true }

'0x00047400008fd937':
  friendly_name: Shutter_Office
  device_options:
    invert_cover: true

'0x00047400008fd937':
  friendly_name: Shutter_Office
  invert_cover: true
```

**Comment by eRJe79** [comment]
OK, nevermind... After coming home at the end of the day, "suddenly" the following syntax was working"

```
'0x00047400008fd937':
  friendly_name: Shutter_Office
  invert_cover: true
```

I guess I was to quick testing my changes before.

**Comment by EDelsman** [comment]
If I understand this correctly I need to edit settings in the web UI because config.yaml is overwritten on boot. 
This is bad design, because the GUI won't boot until I reconfigure. That is because I own a Conbee II, which states:
If Zigbee2MQTT fails to start, try adding the following to your configuration.yaml

serial:
  adapter: deconz

That line gets overwritten, and I never get a GUI to begin with.

**Comment by joshuaspence** [comment]
I have made an attempt at improving this in #270. Basically, I have removed all Z2M specific configuration from the addon. Z2M configuration can now be managed either by directly modifying `zigbee2mqtt/configuration.yaml` or using the UI. If you want to try out my PR you can add my repo as an addon repository: https://github.com/joshuaspence/hassio-zigbee2mqtt. Please note that I didn't pre-build the Docker images so it will take 10 minutes or so to install via my repo.
