### ISSUE TITLE
Cannot see any configuration options

### ISSUE THREAD

**Issue by Shivy011** [zigbee2mqtt/hassio-zigbee2mqtt#439]
### Description of the issue

Hi, I can only see this in my config when I install the add-on:

enabled: false
master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
options: "-d -d"
log: false

I can't add my mqtt username etc, any ideas how I can do this?

### Addon version

1.29.0-1

### Platform

Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**Comment by ericvb** [comment]
First of all, I'm also a newbie trying to install this addon with a CC2652P2 TCP Zigbee Coordinator from cod.m

When you say : _Hi, I can only see this in my config when I install the add-on:_
Do you mean, in the Configuration tab of the add-on?
![image](https://user-images.githubusercontent.com/3419875/210749847-5cd30fa8-5f02-4e5e-9b1c-d47cd06b7392.png)
At first I didn't have also these entries, so I did go by 'Edit in yaml' at the 3 dots menu, to add them.

I wonder where this configuration is written, because in the specific zigbee2mqtt configuration yaml file, I do not see this configuration, only this:
![image](https://user-images.githubusercontent.com/3419875/210750380-0f28caf4-d18f-483c-83dd-1779c5ce8a6e.png)

But now it is failing with this:
![image](https://user-images.githubusercontent.com/3419875/210750835-c2131161-67be-4fa1-a6ab-e2babcc8fa44.png)
Searching further :-)
