### ISSUE TITLE
Availability not working

### ISSUE THREAD

**Issue by Sirmike2** [zigbee2mqtt/hassio-zigbee2mqtt#481]
### Description of the issue

Scenario: I have a light that can I power on and off with a regular switch. If I power on the light it will be recognized by Z2M and the availability changed to online. Than I switched off the light, but the status will not change to offline.
If I activate Availability (advanced) the device should go to offline if it is not reachable. Also there should be a ping from time to time, but there is no pinging at all.

### Addon version

1.30.3-dev 

### Platform

Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest

**Comment by ZTHawk** [comment]
I have the same issue.
Active devices should be marked as offline after one minute.
The devices are not reachable since one day (because I have switched them off) but are still marked as online:
![grafik](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/23618799/4d8e38d2-9f10-4884-b3ab-8acd3244da6e)
