### ISSUE TITLE
Impossible OTA for NodOn  SIN-4-RS-20

### ISSUE THREAD

**Issue by mitch55500** [zigbee2mqtt/hassio-zigbee2mqtt#514]
### Description of the issue

ZigbeeMQTT finds an updatefor the firmware of my NodOn SIN-4-RS-20 but can't do it.

### Addon version

1.32.1-1

### Platform

Home Assistant 2023.7.3
Supervisor 2023.07.1
Interface utilisateur : 20230705.1 - latest

### Logs of the issue (if applicable)

Zigbee2MQTT:info  31-07-2023 19:17:34: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"NodOn 1"},"error":"Update of 'NodOn 1' failed (No image available for imageType '265')","status":"error","transaction":"zbgyj-1"}'
Zigbee2MQTT:error 31-07-2023 19:17:34: Update of 'NodOn 1' failed (No image available for imageType '265')
Zigbee2MQTT:debug 31-07-2023 19:17:34: Error: No image available for imageType '265'
    at getImageMeta (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/zigbeeOTA.ts:114:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getNewImage (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:437:18)
    at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:296:19)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:267:41)

**Comment by Koenkk** [comment]
This means we don't have an image available for your device, you can try asking NodOn if they can provide the OTA.

**Comment by mitch55500** [comment]
It's strange : NodOn Connect (Android Application) tell me my products are up to date.

**Comment by nanostra** [comment]
> It's strange : NodOn Connect (Android Application) tell me my products are up to date.

Same problem with several SIN-4-1-20 and SIN-4-2-20

**Comment by rockyhopper** [comment]
Home Assistant (with zigbee2mqtt add-on) is reporting my Nodon "SIN-4-1-20" update  from version "534" to ¨541".

- Trying to trigger update from Home assistant fails.

- Trying to trigger update from Zigbee2Mqtt frontend is resulting in "Update of 'PriseTerrassePergola' failed (No image available for imageType '266')¨.
Looks like due to message received from the device:
" Received Zigbee message from 'PriseTerrassePergola', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":65794,"imageType":266,"manufacturerCode":4747}' from endpoint 1 with groupID 0 "

- Nodon Android APP to update device is reported that product is up to date.

**Comment by mitch55500** [comment]
If this could help, hereis the message of Nodon technical support : 

`Bonjour Sébastien, 

Nous sommes entrain d'intégrer les mises à jour OTA, c'est pour cela que vous voyez cela apparaitre. 

Pour le moment, il n'y a pas de nouvelle mise à jour disponible.
Les dernières versions sont celles publiées sur NodOn Connect. 

Bonne journée. 

Cordialement, 
`

**Comment by dajudge** [comment]
This still seems to be unsolved, right?
