### ISSUE TITLE
zigbee2mqtt wont start - MQTT error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by geidorei** [zigbee2mqtt/hassio-zigbee2mqtt#530]
### Description of the issue

After core update this week zignbee2mqtt wont start:
Zigbee2MQTT:error 2023-11-11 12:15:25: MQTT error: connect ECONNREFUSED 172.30.33.0:1883
Zigbee2MQTT:error 2023-11-11 12:15:25: MQTT failed to connect, exiting...

I have not changed any settings and also looked for a solution, to no avail. Passwords etc are correct.

This is what I have done so far:
Rebooted
Turn RPi4 on/off
Unplugged the Sonoff stick CC2531, and also the extension cable, swapped USB ports, swapped cables....
Confirmed LED is on. 

Any suggestions and help much appreciated. Thanks folks.

### Platform

Core 2023.11.2
Supervisor 2023.11.0
Operating System 11.1
Frontend 20231030.2

### Logs of the issue (if applicable)

[12:15:06] INFO: Preparing to start...
[12:15:07] INFO: Socat not enabled
[12:15:12] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:error 2023-11-11 12:15:25: MQTT error: connect ECONNREFUSED 172.30.33.0:1883
Zigbee2MQTT:error 2023-11-11 12:15:25: MQTT failed to connect, exiting...

MQTT:
2023-11-11 12:20:13: Warning: Mosquitto should not be run as root/administrator.
mosquitto: persist_read.c:550: persist__restore_sub: Assertion `client_id' failed.
[12:20:15] INFO: Successfully send discovery information to Home Assistant.
[12:20:15] INFO: Service restart after closing
[12:20:16] INFO: Successfully send service information to the Supervisor.
[12:20:17] INFO: Starting mosquitto MQTT broker...

Which I believe is AOK.

**Comment by geidorei** [comment]
Sussed it - FYI for anyone else who has this issue.

It was down to a corrupt MQTT database. To fix this I copied the YAMA config, and then uninstalled, reinstalled and put the original YAML back. Fixed!

**Comment by BrianHenryIE** [comment]
Thanks.

I fixed with:
* stopped the containers (eclipse-mosquitto and koenkk/zigbee2mqtt)
* moved the database `mv database.db database.db.old` (path is defined in the Dockerfile yaml `services:.zigbee2mqtt.volumes:`)
* started the containers
* visited Zigbee2Mqtt and it loaded but with no devices
* stopped the containers
* deleted the new database and moved the old database back `rm database.db; mv database.db.old database.db`
* started the containers

I'm not sure why that worked, but it did! I had stopped and started them a couple of times already, and updated to the latest version.

I should probably back everything up.
