### ISSUE TITLE
How to switch to the new repository without losing all my configs and devices?

### ISSUE THREAD

**Issue by Furegato** [zigbee2mqtt/hassio-zigbee2mqtt#54]
I am stuck with release 1.17.1-4. So I've read that I need the new repository link. However, when I add the new repository, It does not update the existing zigbee2mqtt, it creates a new one, therefore all me settings and devices are "lost".
Is there a way to update to the latest release without losing all my setting, configs and devices?
Thanks a lot.

zigbee2mqtt add-on version 1.17.1-4

Current repository:
Home Assistant Add-on: Zigbee2mqtt
Daniel Welch <dwelch2102@gmail.com>
https://www.zigbee2mqtt.io

```
Core: core-2021.3.1
Supervisor: supervisor-2021.03.4
Operating System: HassOS 5.12
```

**Comment by shokwaav** [comment]
I copied the configuration over into the new add on, then I copied all the files in the \share\zigbee2mqtt folder to the new \config\zigbee2mqtt folder.

Then I stopped the old zigbee2mqtt add on, uninstalled it, and started the new zigbee2mqtt 1.18 one. Everything seems to have copied over fine.

Create a snapshot just in case.

**Comment by ciotlosm** [comment]
Check how to switch here: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/52#issuecomment-792873888

No copying needed, unless you really want to use the new default `/config/zigbee2mqtt` folder instead of the older model with `/share`.  As this path is in the config, you control where the add-on searches for it's files, so that's why you can do it seamless just by copy/pasting the config.
