### ISSUE TITLE
Add-on doesn't start - unknown option restartdelay, initialdelay and new_api

### ISSUE THREAD

**Issue by raffalbednarz** [zigbee2mqtt/hassio-zigbee2mqtt#55]
i cant connect  again BW_SPH13 
![image](https://user-images.githubusercontent.com/76666901/110235653-a5fedb00-7f31-11eb-8967-458b16d5dc2b.png)

Zigbee2mqtt
Current version: 1.17.1-4

```
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:32:32 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-03-07 09:33:10 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt
```

**Comment by ciotlosm** [comment]
As the errors show, you have some options that got removed some time ago:

restartdelay, initialdelay and new_api

Please remove those from your config and z2m should start.

**Comment by raffalbednarz** [comment]
thank you very very much i removed it and SPH13 now is working!

**Comment by gorunf** [comment]
Same thing, but i cant remove this options. I cant find actual config location. Change config with WEB dosent work.
My system is hassio+raspbery pi 3

P.S.: Sorry foe my English

**Comment by xpavli44** [comment]
@gorunf see https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-795604653

**Comment by raffalbednarz** [comment]
> Same thing, but i cant remove this options. I cant find actual config location. Change config with WEB dosent work.
> My system is hassio+raspbery pi 3
> 
> P.S.: Sorry foe my English

![image](https://user-images.githubusercontent.com/76666901/110673835-8be32800-81d1-11eb-90c1-1f4a6b833d22.png)

**Comment by xpavli44** [comment]
@raffalbednarz perfect description of where to find it in WEB .... the problem is that the WEB does not let you to change the config, you press save and it just overwrites your changes back ... I believe @gorunf was referring to finding it in the haas file system ... the only solution for me was to remove the addon as per https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-795604653 I lost my zigbee devices in the process as I forgot to back them up

**Comment by raffalbednarz** [comment]
@xpavli44 a ok sorry i didn't know can be like that,  thank you for the explanation :-) good knowledge about next future problem

**Comment by klosz007** [comment]
No idea why you were not able to edit config from GUI. Stop Zigbee2MQTT, change config (remove excessive options), save, start service again, problem fixed for me. It does not let you to save modified config if there are syntax errors in it.

**Comment by xpavli44** [comment]
One of the mistakes I made and realised only later on was that I was trying to remove whole **experimental: {}** section.

**Comment by diagonali** [comment]
I'm having very similar problems which I've reported separately here: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/77

Video of strange addon/home assistant UI behaviour: https://i.imgur.com/hVQ44oO.mp4

Was/is causing a nightmare since no matter whether I edit the config files directly, or using the Home Assistant UI, I keep getting
`21-04-01 13:15:00 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-04-01 13:15:00 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-04-01 13:15:00 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)`

It's like the addon is storing the config file _somewhere_ I can't find and keeps using that cached version instead of the one I either edit manually or with the UI. Really hope this is a known bug and will be fixed soon as it's actually quite a serious issue in terms of preventing using the addon normally.

**Comment by klosz007** [comment]
It's not a bug, these options were removed form Zigbee2MQTT so it doesn't recognize them. Unfortunately they must be reomved form conifg manually.

As I wrote above, this is very easy to fix:
- stop Zigbee2MQTT addon
- edit conifg file from UI to remove these old/unsupported options
- press Save button
- if config file returns to previous form, it means there is syntax error in the new config file -> fix it
- if there is no syntax error, edited version will appear
- start Zigbee2MQTT addon
- error messages will be gone

**Comment by diagonali** [comment]
@klosz007 Thanks very much for your reply and instructions.

I've followed them exactly and seem to have "fixed" the issue after quite a lot of remaining strange behaviour in the UI.

There definitely seems to be a bug in the UI when displaying the config file (like in the video clip I posted) as it's still happening now even with no errors or syntax issues. I'm guessing it's something to do with it being converted to/from YAML?

So the problem for me is "solved" but the bug persists in the config editor UI which makes editing the config difficult and confusing - hopefully it will get fixed in next release.

**Comment by klosz007** [comment]
Yes, handling of errors in the UI config editor could be better. Some obvious issues (such as unclosed brackets) will be immediately reported and Save button will be deactivated but lack of brackets at all etc. will not be reported, Save button will be then active, but parsing will fail upon pressing Save with no error messages and editor then silently reverts to original file. This may be very misleading - one may thing that file cannot be edited. I'm guessing this is not Zigbee2MQQT issue but HA issue.

**Comment by diagonali** [comment]
@klosz007 
There are also some other weird anomalies. For example, when I view the configuration for zigbee2mqtt in HA, it doesn't seem to match the file "configuration.yaml" when I view this using the VSCode addon in HA.

My config when viewed in HA:
`data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: xxxx
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  log_level: warn
  pan_id: 6759
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
ota:
  disable_automatic_update_check: true
`

But in VSCode it shows:
`{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "mqtt",
    "password": "xxxx"
  },
  "serial": {
    "port": "/dev/ttyUSB0"
  },
  "advanced": {
    "rtscts": false,
    "log_level": "warn",
    "pan_id": 6759,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {}
}
`
Which among other things doesn't include any reference to the "data_path". This is making tracking the effect of changes _extremely_ difficult.

For example, I've tried adding
`ota:
    disable_automatic_update_check: true`

To my config using the HA ui but this causes a warning in the HA system logs:
`WARNING (MainThread) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt`

Normally, I'd sidestep the issues with the HA ui for editing configs by editing the config file directly using the VSCode plugin but I have no idea why the VSCode plugin seems to be reading a different file or where it's getting its values from.

Should I submit a bug report somewhere directly? To the HA devs or here for zigbee2mqtt?

In the meantime, I don't understand why editing the file directly shows a different config to the one shown in the HA ui beyond obvious syntax difference. I also can't figure out how to disable ota automatic update checks since even with what I believe to be the correct syntax in the HA ui, it claims there is no "ota" in the schema!

**Comment by klosz007** [comment]
My suspicion is that the conifg file, as displayed in the GUI, is kept somewhere in the Z2M plugin's docker. When you save it, it is converted into actual 'running' config file. I was once trying to find out where the 'displayed' config is stored but I couldn't find it. Or maybe it is 2-way conversion ? I.e. what is dislapyed in the configuration page is first converted from actual configuration, and when it is saved, it is converted again to actual config file again ?
I agree it is confusing/weird/overcomplicated.

BTW, if you want to disable OTA update check then proper way is to go to plugin's own GUI -> Settings -> OTA updates -> check "Disable automatic update check".

**Comment by diagonali** [comment]
@klosz007
Ah that does make sense. I looked inside the docker container files but couldn't find it either and gave up.

I have actually tried using the GUI (which is great) to disable OTA update checks but as with other weirdness I'm experiencing with the addon (it's not updating to latest version am currently stuck on version: 1.18.1-1), when I restart the addon, the option "Disable automatic update check" keeps being unchecked. I might have to do a backup and do a fresh install of the addon.

**Comment by somar05** [comment]
> It's not a bug, these options were removed form Zigbee2MQTT so it doesn't recognize them anymore, hence these error messages. Unfortunately these options must be removed form conifg file manually.
> 
> As I wrote above, this is very easy to fix:
> 
> * stop Zigbee2MQTT addon
> * edit Zigbee2MQTT conifg file from UI to remove these old/unsupported options
> * press Save button
> * if config file returns to previous form (before editing), it means there is syntax error in the new config file -> fix the error, use Save button again
> * if there is no syntax error, edited version will appear
> * start Zigbee2MQTT addon
> * error messages will be gone
> 
> I do not remember where exactly in the config file these options were located, here's how it should like after removal (just portion of the config file):
> device_options: {}
> blocklist: []
> passlist: []
> queue: {}
> frontend:
> port: 8099
> experimental: {}

First, thanks for the comments to resolve the issue with the config from the UI. Just as note, I had to restart HA after save the config and before start Zigbee2MQTT addon. After that, the UI config was saved properly. Just saving config and starting the addon was not enough in my case.
