### ISSUE TITLE
Add-On Crashes Often

### ISSUE THREAD

**Issue by darthrater78** [zigbee2mqtt/hassio-zigbee2mqtt#561]
### Description of the issue

I'm rapidly approaching complete failure of the SAF (spousal approval factor) for Z2M. I switched from ZHA about two months ago, and for the first month everything was fantastic. Lately though the add-on has been hard crashing, the watchdog doesn't restart it and when it goes down it turns on every light in the house at 100% brightness. 

When this happens at 2am, it's not a good scene when the bedroom turns into the face of the sun. 

After I restart the app, every light is offline, and I have to turn on inclusion and cycle the light switches on and off and the majority hop back on. One or two have to be completely re-paired.  

I don't know how to troubleshoot this or check logs since it seems that history is lost when the app crashes. 

I am using UZG-01 as a LAN coordinator. The ESP firmware was 1.5, so I upgraded to 2.0 and the coordinator is at the latest firmware of 20230507.

I have a combo of cree and GE lights. 

My non-light devices seem to come up fine without any intervention. 

### Addon version

1.35.1-1

### Platform

Core: 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by NicoBenndorf** [comment]
I have a similar issue where all zigbee devices stop working and I have to restart the zigbee integration. Watchdog solves nothing but it also seems like the integration does not crash but just stops working properly..
At least they don’t all turn on when this happens 😅 but still it is very unusable - this happend multiple times per day recently.

I recently added two zigbee mmWave sensors that publish a lot of updates and I also worry that they spam the network and create/worsen this problem.

When i look at the logs it is hard to see anything since the mmWave sensor send so many updates. 
any advice how to debug this?

**Comment by cropse** [comment]
Same here, I have to restart add on every several hours.

**Comment by darthrater78** [comment]
When I turned the Availability to simple from advanced things calmed down and I’ve been very stable for the last week or so.



![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/94141126/38d5a071-a5d9-4bae-83e9-2ce707454d49)

**Comment by jpguyon52** [comment]
Got the same error since 2 weeks. 
Found out the first log that seem to start the crash a few minutes after restart. 

Zigbee2MQTT:error 2024-02-07 17:38:44: Failed to configure 'OfficeMotionSensor1', attempt 1 (Error: Read 0x54ef44100049068a/1 manuSpecificLumi([338], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 60229 - 1 - 201 - 64704 - 1 after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:502:47)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:466:28)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/lumi.ts:1781:13)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:141:25)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
