### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by erwindouna** [zigbee2mqtt/hassio-zigbee2mqtt#610]
### Description of the issue

The add-on is not able to show the web-ui in Home Assistant. It throws an unexpected token:

![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/5011203/4b63c80d-4457-495b-a801-bcee09d43899)

![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/5011203/5eb36b85-ad97-4bae-aacf-1008c608b72b)

Other users also seem to be experiencing this [issue](https://community.home-assistant.io/t/zigbee2mqtt-web-ui-stopped-working-blank-page/726965).

What works as a _solution_, is to completely reinstall the add-on.

### Addon version

1.37.1-1

### Platform

Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

**Comment by SergeyPomelov** [comment]
The same. Just broken after few days after install, HAOS restarts does not help, an addon reinstall - does.

**Comment by anordvall** [comment]
I also have the exact same issue.

**Comment by nedievas** [comment]
> The same. Just broken after few days after install, HAOS restarts does not help, browser caches sweep - does not, an addon reinstall - does.

Do you have to rejoin the devices after add-on reinstall?

**Comment by SergeyPomelov** [comment]
> Do you have to rejoin the devices after add-on reinstall?
No, I haven't, but I'm not 100% sure. There are a lot of backup variants - the HA-specific addon backup, the Zigbee2MQTT backup in the UI, or just its folder backup. Anyway, you should make them before proceed, just in case.

**Comment by SergeyPomelov** [comment]
Do the repoowners who are copy-pasting the bot realize that this isn't cleaning the bug tracker, but rather trashing users' input? Most bug reporters will abandon posting and guarding their bugs, leading to a decline in quality that will ultimately drive others away. Instead of discarding informative input, please, mark your components as not actively supported; this would be fair, as there is no obligation to provide support.

**Comment by erwindouna** [comment]
Not stale - still active. Owner still needs to respond.
