### ISSUE TITLE
Not clear how to configure device in zigbee2mqtt Home assistant add-on

### ISSUE THREAD

**Issue by jbrepogmailcom** [zigbee2mqtt/hassio-zigbee2mqtt#91]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

I had separate installation of zigbee2mqtt and in configuration.yaml there was section with automatically paired devices. However, in the add-in, in configuration there is `devices: devices.yaml` Your documentation does not say if already paired devices should be put into the add-on configuration *instead* of `devices.yaml`, or if existing devices should be put into some file called devices.yaml and where this file should be located.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.2.2
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.4
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```

**Comment by netweaver1970** [comment]
same he, I also want to do the migration and I could use some better guidance on how to do the move without having to re-pair and reconfigure everythigng.

**Comment by jbrepogmailcom** [comment]
Pairing in add-on did not work, devices that I paired on first try in standalone installation just paired after twenty attempts on add-on. And it was paired as new device. When I saw this and I imagined I will have to reconfigure lovelace and all my automations, I gave up, restored HA from Yestarday and installed zigbee2mqtt in new computer as standalone again and copied over original data directory. Everything started to work immediately. So I do not recommend migration from standalone installation to add-on, costed me 4 hours of my life.

**Comment by Hostiss** [comment]
Yeah, but this actually might be because of a completely different issue. Last time I was moving in a second location, from CC2531 to CC2652R, and I have experienced the same issues, as I was doing migration for the first time. Basically, this is especially true for my Xiaomi temperature&humidity sensors, some devices can have enough power to work normally without any problems (even showing very high battery level), but don't have enough power to do pair process. For me, putting a brand new battery was the only solution to finish the pairing process. You should try this too, it might not be related to zigbee2mqtt at all. 

Speaking of showing as a new device, it mostly comes from the "friendly name" field in Zigbee2mqtt- it's quite annoying and I did notice that too. From my understanding, If you have a brand new device, it's registering in the MQTT using his IEEE address (so like binary.sensor.0x00111e0003c49ccf0), and your older devices are probably registered under a "friendly_name" which you likely set some time ago in zigbee2mqtt (like binary.sensor.Living_room_window). 

I had a couple of devices like that after my first migration, with changed names, so what I did was I made a brand new custom sensors in Node-red, which are named the same as they were before the migration, and connecting them with a new one. So in this example, something like this: 
binary.sensor.0x00111e0003c49ccf0 (the new name after migration, created by zigbee2mqtt) -> sending  its states (like on/off) -> binary.sensor.Living_room_window (the old name before migration, made in node-red)

 By doing that, I didn't have to change all of my automation, which would be pretty annoying.

**Comment by jbrepogmailcom** [comment]
You may be right. The device that I was trying to pair had 50% battery. It did not pair so I reverted back to original setup with working configuration, where device has already been paired earlier. Few hours later, device died because of battery, last battery status before dead was 50%. It was temperature sensor. I have read, that if device wants to get Zigbee certification the battery have to last at least 2 years. Apparently not those bought on aliexpress....

**Comment by ciotlosm** [comment]
Is this issue still valid? if you reference and external config in the addon like specified above that is not managed by the add-on. The functionality is something for Core. 

You should open an issue here: https://github.com/Koenkk/zigbee2mqtt/issues if you are still having issues.

**Comment by krzyk** [comment]
Issue with addon is that the number 2 (first being just adding devices) use case for it is migrating from standalone zigbee2mqtt and it is not described anywhere how to do it (as you can see from comments above).

I struggle with that myself and as you can see I'm not alone.

I don't know how to add new devices using addon, what is the devices.yml file and where I could see it, etc.
